server:
  port: 8080

spring:
  application:
    name: "accounts"

  config:
    import: "optional:configserver:http://localhost:8071/"

  profiles:
    active: "dev"

  logging:
    level:
      my:
        micro:
          accounts: DEBUG

  eureka:
    instance:
      preferIpAddress: true
    client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
        defaultZone: http://localhost:8070/eureka/

  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root
    jpa:
      show-sql: true
    sql:
      init:
        mode: always

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true