server:
  port: 8080

spring:
  application:
    name: "accounts"

  profiles:
    active: "dev"

  config:
    import: "optional:configserver:http://localhost:8071/"

  logging:
    level:
      my:
        micro:
          accounts: DEBUG

  datasource:
    url: jdbc:mysql://accountsdb:3306/accountsdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true