server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    #active: native
    active: git

  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//o_narit.c//WorkSpace//MY//MY-TEST-SPRING-3//udemy//MasterMicroservice//configserver//src//main//resources//config"
        git:
          uri: https://github.com/recycleid/MY-TEST-SPRING-3.git
          searchPaths: /udemy/MasterMicroservice/configserver/src/main/resources/config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: 34d2e4255c8e6beb3c42f24dfd7e6da9

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true