---
version: '3.8'
services:
## data flows
  db-ctable:
    container_name: db-ctable
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_DB: ctable
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - ./volumn/db-ctable:/data/postgres
    ports:
      - 5431:5431
    expose:
      - 5431
    restart: always

  db-space:
    container_name: db-space
    image: mongo:7.0-jammy
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./volumn/db-space:/data/db

  db-keycloak:
    container_name: db-keycloak
    image: mariadb:11.3-jammy
    restart: always
    ports:
      - 4306:4306
    expose:
      - 4306
    volumes:
      - ./volumn/db-keycloak-data:/var/lib/maria
    environment:
      MARIADB_DATABASE: keycloak
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: root

  broker:
    image: confluentinc/cp-kafka:7.6.0
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./volumn/kafka/data:/var/lib/kafka/data
  
  redis:
    image: redis:7.2.4-alpine3.19
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./volumn/redis_data:/data
    restart: always

## ids
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:24.0
    command: [ start-dev, --import-realm ]
    environment:
      DB_VENDOR: MARIADB
      DB_ADDR: db-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8791:8791
    expose:
      - 8791
    volumes:
      - ./volumn/realms/:/opt/keycloak/data/import/

## config - discovery


## config discovery tracing metrics logging
  spring-boot-admin:
    image: codecentric/spring-boot-admin:3.0.0-M6
    container_name: spring_boot_admin
    ports:
      - 9050:9050
    expose:
      - 9050
    volumes:
      - ./volumn/spring_boot_admin:/config
    restart: always

  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    restart: always
    ports:
      - 9051:9051
    expose:
      - 9051
    volumes:
      - ./volumn/prometheus/:/etc/prometheus/

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    restart: always
    ports:
      - 9052:9052
    expose:
      - 9052
    volumes:
      - ./volumn/loki/:/etc/loki/

  tempo:
    image: grafana/tempo:2.4.0
    container_name: tempo
    restart: always
    ports:
      - 9053:9053
    expose:
      - 9053
    volumes:
      - ./volumn/tempo/:/etc/tempo/

## ui
  grafana:
    image: grafana/grafana:10.4.0
    volumes:
      - ./volumn/grafana:/etc/grafana/provisioning/datasources:ro
    restart: always
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 9100:9100
    expose:
      - 9100

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9101:9101
    expose:
      - 9101
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./volumn/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    ports:
      - 9102:9102
    expose:
      - 9102
    volumes:
      - ./volumn/redis_insight:/db
    restart: always